import { test, expect } from '@playwright/test';

test('Login to Program Dashboard and verify the home page UI', async ({ page  },testInfo) => {
  await page.goto('https://www.metrics-portal.philips.com/program_board');
  //await page.goto('https://login.microsoftonline.com/1a407a2d-7675-4d17-8692-b3ac285306e4/saml2?SAMLRequest=fVLLbtswEPwVgXfqQT1DWAac%2BFADaWrETg%2B9BBS1ighQpMqlouTvK9sJ6lxy3tmZnZldoRj0yDeT780j%2FJ0AffA2aIP8PKjJ5Ay3AhVyIwZA7iU%2FbH7ecxbGfHTWW2k1CTaI4Lyy5s4anAZwB3CvSsLT431Neu9H5FE0z3M4gHdKIh2t80KHY6%2B0GjGUdogWtrf36NCrprEafB8i2uikxaL9r8ORBNvlOGXESeY%2FqbYvyoSDks6i7bw1Whk48yUii0vBWloWZU6zNilpVdww2qRCsipP4wKy6OSSkWC3rclzkVVtATLtuptGQpXmeddAVnZlC0ymSbvAECfYGfTC%2BJqwmGU0LmlcHZOEs5jn%2BR8S7D9CuVWmVebl%2BwSbCwj5j%2BNxTy82f4PDs8UFQNar04X8LOyumvmeVnzWQdafOYmlYTfSJeSWihlpEl%2BHv4quZC6aI39YeHfbvdVKvgcbre1850B4qElCovVl5evrrP8B&RelayState=ss%3Amem%3A1d0ef487beddef3c2ac8683de0dc97328c259e2363e2af1ae34709bf2e880272');
  //await page.goto('https://login.microsoftonline.com/1a407a2d-7675-4d17-8692-b3ac285306e4/saml2?SAMLRequest=fVLLbtswEPwVgXfqQT1DWAac%2BFADaWrETg%2B9BBS1ighQpMqlouTvK9sJ6lxy3tmZnZldoRj0yDeT780j%2FJ0AffA2aIP8PKjJ5Ay3AhVyIwZA7iU%2FbH7ecxbGfHTWW2k1CTaI4Lyy5s4anAZwB3CvSsLT431Neu9H5FE0z3M4gHdKIh2t80KHY6%2B0GjGUdogWtrf36NCrprEafB8i2uikxaL9r8ORBNvlOGXESeY%2FqbYvyoSDks6i7bw1Whk48yUii0vBWloWZU6zNilpVdww2qRCsipP4wKy6OSSkWC3rclzkVVtATLtuptGQpXmeddAVnZlC0ymSbvAECfYGfTC%2BJqwmGU0LmlcHZOEs5jn%2BR8S7D9CuVWmVebl%2BwSbCwj5j%2BNxTy82f4PDs8UFQNar04X8LOyumvmeVnzWQdafOYmlYTfSJeSWihlpEl%2BHv4quZC6aI39YeHfbvdVKvgcbre1850B4qElCovVl5evrrP8B&RelayState=ss%3Amem%3A1d0ef487beddef3c2ac8683de0dc97328c259e2363e2af1ae34709bf2e880272&sso_reload=true');
  await page.getByPlaceholder('someone@example.com').click();
  await page.getByPlaceholder('someone@example.com').fill('partner.venkatesh.kadlur@philips.com');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('#i0118').fill('Cloud@0046');
  //await page.locator('#i0118').press('Enter');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.waitForTimeout (20000);
  await page?.waitForSelector("text=SW Development KPI Dashboard", { state: `visible` });
  const text = await page.locator("text=SW Development KPI Dashboard").textContent();
  console.log("-----------------------------------------------------------------------");
  console.log("Program Dashboard Text"  ," : ", text);
  //console.log("-----------------------------------------------------------------------");
  await page?.waitForSelector("text=Track, analyze, and optimize", { state: `visible` });
  const text1 = await page.locator("text=Track, analyze, and optimize").textContent();
  console.log("-----------------------------------------------------------------------");
  console.log("Validation Text"  ," : ", text1);
  //console.log("-----------------------------------------------------------------------");
  await page?.waitForSelector("text=KEY PROGRAM METRICS", { state: `visible` });
  const text2 = await page.locator("text= KEY PROGRAM METRICS").textContent();
  console.log("-----------------------------------------------------------------------");
  console.log("UI validation text"  ," : ", text2);
  console.log("-----------------------------------------------------------------------");
  await page.getByRole('button', { name: 'Defect Escape Ratio' }).click();
  //await page.waitForTimeout (20000);
  await page.locator('div').filter({ hasText: /^BusinessesSelect\.\.\.$/ }).locator('svg').click();
  await page.getByRole('option', { name: 'Enterprise Informatics' }).click();
  await page.waitForTimeout (20000);
  await page.locator('div').filter({ hasText: /^Business UnitsSelect\.\.\.$/ }).locator('svg').dblclick();
  await page.getByRole('option', { name: 'PCI' }).click();
  await page.waitForTimeout (20000);
  await page.locator('div').filter({ hasText: /^ProgramSelect\.\.\.$/ }).locator('svg').click();
  await page.getByRole('option', { name: 'ROCC' }).click();
  await page.waitForTimeout (20000);
});